.travis.yml:
  sudo: true
  services:
    - rabbitmq
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      - TEST_TYPE=medium
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: CX57N9CLMwqB3Vw0ftIdVYugkJYMFvkNlP8n0yB8P9g2rGSJxC5TnWISmvK6EFHXvrZQPCEZbmTolOePpQ530qLQkDtAahrVzkWXNkCH4bG6bd5pEM8ywAOtIEaUkSCRy8At/2QSUgaf4fOd4eve5sY+63QJqiNbseqf30m8OJaQUmVqLB1YHa2tTkT6yqZaWjWQ6QBdd+d7mrorTKr0G4n5QZOau1z0zSej703tObCINLW4l/7Kn863WtXuw2V9+3ZzQhEEQqxVL4s0alWDWcWIPHE5N2brmW33Lp4iYEAK9A9bHK++32fJmS4QSwL2IJ+23sUyHBBaO70UIBs7t5wN9tUCRR8CkdieQYdfIqtP/Ia1PE1oxGPJUmQN+gQj+PnXGzbB+fNSBfjY+NoqPQJ4+v0pH7oTAcRDvgAF1k39tiZiXN10RFJYwS2bJ+VzU7H7+t6CcopYlaJzRUU+YKMkRvqJ8PIpv1UJtsARYj4CEDuJrEUG0CQ785DV5M4SUdRJfvlUbEy9rf2XuDGvD1Lb/pjIbRZtbs6aPxQzHkVsbm5ARxJqlHFY3/ZGpu3pri+TLvr+Tx77XWK+EMurhdrPAi32eC3c0N5z7aPDuINVgrl17rh6kw6Xmy4L2fJUpl5KuuaA/AE+bM1Yopk/P1z0F0zu0Yw7ZBVE88wOIlo=
    api_key:
      secure: iywk4kfiTy5bjP2uSTkdv4V+Q1LFxB7HIQ/leJGUOrNXljQJQakzwaPTqBaTwOZHAVqXo+JT91YV42OnL2dp4+XmJEAQQ7FzD3ystMwBhgp00K27dTWwQTIlSnwM6l+5qxPOa4d2MdWPon2FJj7KsU3t/doFrd1pck2Zd51lEE7WX2cfEoIOOnCQoc5515D4gDh90ht2OlBoVp3Ica81EGgiPwyQWjbWuzSTV2WBtGVau5o/G++tby+7M7adsQrFZFgoXAZbPbXD9TNTBPqMDs1bnNcPjKE5V7YQH0+XsNKOrg0++NPfhFtIoxOFn0ysjSEZp5JGW87Y/+ldfCpYNoqhOm9FUr9+Er6Xa5WTAKR/2Na2pD4raQCrQxmva4QRKXZrSbaO//Suj0pcVcZu0LR4RcDyjL3Ws3Wf+xtMsOUC4aKEHEDKzdoCMIebgd0Pq7H4J+TpDsW7gpJH2qS5uD9oFh9BmDiseMwmbZzh9fxSSawgguXlEGbuRuyLmlD5wgQBMSYM52n/etLO+PPmb0nv8TJcpcWzhAZoZVz9fAQt4Beu4zTdr8qETJd1v9TKeBibUaVnRttZbfxfLlyhgePo6nuwrll/Qwled/38d5NRHmaILM9s2cFxgfTB1qjWZsw+2gBSN1+dAggLb63gE/4q+rDv+24JWAzRTsHe0IA=
